### ISSUE TITLE
translate spanish

### ISSUE THREAD

**Issue by Benzitczo** [Nearata/flarum-ext-twofactor#17]
Okay, here is locale > create es.yml

here full code:
``` yml
nearata-twofactor:
  admin:
    settings:
      generate_app_backups: Generar códigos de respaldo de aplicaciones
    permissions:
      can_enable_twofactor: Puede habilitar dos factores
  forum:
    settings:
      section_title: Autenticación de dos factores
      configured: Configurada
      not_configured: No configurada
      app:
        button_label: Aplicación de autenticación
        button_help: Recibirás un código de acceso a través de tu aplicación de autenticación.
          title: Recibirás un código de acceso a través de tu aplicación de autenticación.
          password_placeholder: Contraseña
          passcode_placeholder: "Código de acceso de 6 dígitos"
          close_button_label: Cerrar
          invalid_passcode: Contraseña o código de acceso no válido.
          disable:
            enter_code_disable: Introduzca el código para desactivar la aplicación de autenticación de dos factores.
            button_label: Deshabilitar
            success: APP de autenticación deshabilitada.
          enable:
            button_label: Habilitar
            success: Aplicación de autenticación habilitada.
            scan_qr: Escanee este código QR con su dispositivo de autenticación de dos factores para configurar su cuenta.
            enter_code_manually: Ingrese la clave manualmente en su lugar
            backups:
              message: >
                Guarde estos códigos de recuperación en un lugar seguro.
                Si pierde su dispositivo habilitado para doble factor, estos códigos de un solo uso
                se pueden usar en el orden indicado para iniciar sesión en su cuenta.
              download_button_label: Descargar
              download_file_format: |
                {website_title} | {website_url}

                Guarde estos códigos de respaldo en algún lugar seguro pero accesible.

                LISTA DE CÓDIGOS

                {codes}

                * Solo puedes usar cada código de respaldo una vez.
                * Estos códigos DEBEN usarse en el orden indicado.
                * Estos códigos se generaron en: {date}.
              copy_button_label: Copia
    login:
      title: Autenticación de dos factores
      placeholder_label: Elija un método de autenticación...
      submit_button_label: Iniciar Sesión
      auth_buttons:
        app: Aplicación de autenticación
      app:
        invalid_passcode: Código de acceso inválido.
        passcode_placeholder: "Código de acceso de 6 dígitos"
  lib:
    edit_user:
      section_title: Autenticación de dos factores
      disable_confirmation: ¿Está seguro? Está a punto de desactivar este método de autenticación para el usuario.
      placeholder_text: Nada que deshabilitar
      app:
        label: Aplicación de autenticación

```
